#From this file you can run any simulation
#Import all simulation files 
wd <- getwd()
setwd(wd)
setwd("../logistic")
source("logistic_main.R")
setwd("../multivariate_ddm")
source("mvt_main.R")
setwd("../univariate_ddm")
source("uni_main.R")
#-----------------------------------------------------------------------------------
#------Logistic Between Subjects-----------------------------------------------------------
#-----------------------------------------------------------------------------------
#Parameters
# n: number of participants (does it need to be divided by 2???)
# size: number or trials per participant
# reruns: number of datasets to be simulated (NOTE, if reruns = 1, 
# 10 datasets will be produced, 1 for each probability)
#Output
# aov_p: p-value generated by ANOVA
# glm_p: p-value generated by GLM
# diff_props: difference in proportion of successes between groups
# mean_prop_real: mean proportion of success for both groups combined 
#(meant to converge with prob for large samples)
# g1_prop: proportion of successes for group 1
# g2_prop: proportion of successes for group 2
# n: number of participants
# size: number or trials per participant
# prob :probability of success for an experiment (same for both groups)
#-----------------------------------------------------------------------------------
logistic_data_bs <- simulate_logistic_bs(n = 10, 
                                         size = 10, 
                                         reruns = 1)
#-----------------------------------------------------------------------------------
#------Logistic Repeated Measures-----------------------------------------------------------
#-----------------------------------------------------------------------------------
#Parameters
# n: number of participants (does it need to be divided by 2???)
# size: number or trials per participant
# reruns: number of datasets to be simulated (NOTE, if reruns = 1, 
# 10 datasets will be produced, 1 for each probability)
#Output
# aov_p: p-value generated by ANOVA
# glmm_p: p-value generated by GLMM
# diff_props: difference in proportion of successes between frames(gain vs loss)
# mean_prop_real: mean proportion of success for both frames combined 
#(meant to converge with prob for large samples)
# frame1_prop: proportion of successes for frame 1
# frame2_prop: proportion of successes for frame 2
# n: number of participants
# size: number or trials per participant
# prob :probability of success for an experiment (same for both groups)
#-----------------------------------------------------------------------------------
start_time <- Sys.time()
logistic_data_rm <- simulate_logistic_rm(n = 10, 
                                         size = 10 , 
                                         reruns = 10)
end_time <- Sys.time()
end_time - start_time
save("uni_log_rm_10pp10tr10runs.rda")
#-------------------------------------------------------------------------
#------Univariate BS & RM - identical code for both---------------------------------------------------------
#-------------------------------------------------------------------------
#Parameters
# model: reruns_rm OR reruns_bs, depending on the experiment you want to run
# pp: number of participants
# n: number or trials per participant
# runs: number of datasets to be simulated (NOTE, if reruns = 1, 
# 10 datasets will be produced, 1 for each probability)
#-------------------------------------------------------------------------
univariate_data_bs <- simulate_uni_data(model = reruns_bs, 
                                        pp = 10, 
                                        n = 10, 
                                        runs = 1)
#need to update code downstrem so name of the file is based
#on a model that has been run 
#-----------------------------------------------------------------------------------
#------MVT Between Subjects---------------------------------------------------------
#-----------------------------------------------------------------------------------
#Parameters
# sigma: rda file with drift diffusion parameters from an original model
# mu: combinations of possible drift diffusion model values
# pp: number of participants
# size: number or trials per participant
# runs: number of datasets to be simulated (NOTE, if reruns = 1, 
# 10 datasets will be produced, 1 for each probability)
#Output
# aov_p: p-value generated by ANOVA
# glm_p: p-value generated by GLM
# diff_props: difference in proportion of successes between groups
# mean_prop_real: mean proportion of success for both groups combined 
#(meant to converge with prob for large samples)
# g1_prop: proportion of successes for group 1
# g2_prop: proportion of successes for group 2
# size: number or trials per participant
# pp_g1: number of participants in group1
# pp_g2: number of participants in group2
# Other: mean and sd for all ddm parameters
#-----------------------------------------------------------------------------------
multivariate_data_bs <- simulate_data_mvt_bs(pp = 10, 
                     size = 10, 
                     reruns = 1)
#-----------------------------------------------------------------------------------
#------MVT Repeated Measures---------------------------------------------------------
#-----------------------------------------------------------------------------------
#Parameters
# sigma: rda file with drift diffusion parameters from an original model
# mu: combinations of possible drift diffusion model values
# pp: number of participants
# size: number or trials per participant
# runs: number of datasets to be simulated (NOTE, if reruns = 1, 
# 10 datasets will be produced, 1 for each probability)
#Output
# aov_p: p-value generated by ANOVA
# glm_p: p-value generated by GLM
# glmm: : p-value generated by GLMM
# diff_props: difference in proportion of successes between groups
# mean_prop_real: mean proportion of success for both groups combined 
#(meant to converge with prob for large samples)
# g1_prop: proportion of successes for group 1
# g2_prop: proportion of successes for group 2
# size: number or trials per participant (PER FRAME OR TOTAL - DUNNO)
# pp: number of participants
# Other: mean and sd for all ddm parameters
#------------------------------------------------------------------------------
multivariate_data_rm <- simulate_data_mvt_rm(pp = 10, 
                                             size = 10, 
                                             reruns = 1)
