library(tidyverse)
library(data.table)
library(rtdists)
library(afex)
library(truncdist)
source("mvt_simulation.R")
library(parallel)
library(tmvtnorm)
set_sum_contrasts()
theme_set(theme_bw())
#directory where you want to save the files
wd <- "/Users/ruslanatymchyk/Documents/MSc Behavioural Economics/Dissertation/masters-diss/UPDATED_CODE/simulated_data"
#-----------------------------------------------------------
# distribution: uni, multi
# model: log, ddm
# design: bs, rm
# n: number of participants
# size: number or trials per participant
# reruns: number of datasets to be simulated
name_dataframe <- function(wd, distribution, model, design, n, size, reruns){
  properties <- c(wd, "/",
                  distribution, "_", 
                  model, "_", 
                  design, "_", 
                  n, "pp", 
                  size, "tr", reruns, "runs.rda")
  #each property has to be a string
  newname <- paste(properties, collapse = "")
  #newname <- oldname #make new dataset point to an old one
  print(newname)
  newname
}
#Create data for simulation-----------------------------------------------------
#mu <- c(2.8, 0.2, 1, 0.3, -0.6, 0.50)
#mu: an,st0, sv,t0n, v, z
load("sigma.rda")
#Create lists that contain all combinations of values for simulations-----
combos <- expand.grid(0:8, seq(0, 4, by = 0.5))
combos_all <- combos %>% mutate(an = rep(2.8, nrow(combos)), 
                                st0 = rep(0.2, nrow(combos)),
                                sv = combos$Var2,       
                                t0n = rep(0.3, nrow(combos)),
                                v = combos$Var1, 
                                z = rep(0.5, nrow(combos)))
combos_all$Var1 <- NULL
combos_all$Var2 <- NULL
colnames(combos_all) <- NULL
combos_use <- t(split(t(combos_all), rep(1:ncol(t(combos_all)), each = nrow(t(combos_all)))))
#Note: as there are 81 rows in v_sim and sv_sim, each run of the simulation will 
#produce 81 datasets, one for each comnination of v and sv

#-----------------------------------------------------------------------------------
#------MVT Between Subjects---------------------------------------------------------
#-----------------------------------------------------------------------------------
#Parameters
# sigma: rda file with drift diffusion parameters from an original model
# mu: combinations of possible drift diffusion model values
# pp: number of participants
# size: number or trials per participant
# runs: number of datasets to be simulated (NOTE, if reruns = 1, 
# 10 datasets will be produced, 1 for each probability)
#Output
# aov_p: p-value generated by ANOVA
# glm_p: p-value generated by GLM
# diff_props: difference in proportion of successes between groups
# mean_prop_real: mean proportion of success for both groups combined 
#(meant to converge with prob for large samples)
# g1_prop: proportion of successes for group 1
# g2_prop: proportion of successes for group 2
# size: number or trials per participant
# pp_g1: number of participants in group1
# pp_g2: number of participants in group2
# Other: mean and sd for all ddm parameters

#Run simulation-------
simulate_data_mvt_bs <- function(pp, size, reruns){
  sim_mvt <- mapply(reruns_bs, mu = combos_use,
                                    MoreArgs = list(sigma = sigma, 
                                                      pp = pp,
                                                      size = size,
                                                      reruns = reruns))
  #Code below turns the output into dataframe
  make_df <- function(df){
    df <- as.data.frame(df)
    df <- do.call(rbind.data.frame, df)
  }
  new_mvt <- make_df(sim_mvt)
  new_mvt
  
  file_name <- name_dataframe(wd = wd,
                              distribution = 'multi', 
                              model = 'ddm', 
                              design = 'bs', 
                              n = pp, 
                              size = size, 
                              reruns = reruns)
  save(sim_mvt, file = file_name)
  sim_mvt
}

#-----------------------------------------------------------------------------------
#------MVT Repeated Measures---------------------------------------------------------
#-----------------------------------------------------------------------------------
#Parameters
# sigma: rda file with drift diffusion parameters from an original model
# mu: combinations of possible drift diffusion model values
# pp: number of participants
# size: number or trials per participant
# runs: number of datasets to be simulated (NOTE, if reruns = 1, 
# 10 datasets will be produced, 1 for each probability)
#Output
# aov_p: p-value generated by ANOVA
# glm_p: p-value generated by GLM
# glmm: : p-value generated by GLMM
# diff_props: difference in proportion of successes between groups
# mean_prop_real: mean proportion of success for both groups combined 
#(meant to converge with prob for large samples)
# g1_prop: proportion of successes for group 1
# g2_prop: proportion of successes for group 2
# size: number or trials per participant (PER FRAME OR TOTAL - DUNNO)
# pp: number of participants
# Other: mean and sd for all ddm parameters
#Run simulation-------
simulate_data_mvt_rm <- function(pp, size, reruns){
  sim_mvt <- mapply(reruns_rm, mu = combos_use,
                    MoreArgs = list(sigma = sigma, 
                                    pp = pp,
                                    size = size,
                                    reruns = reruns))
  #Code below turns the output into dataframe
  make_df <- function(df){
    df <- as.data.frame(df)
    df <- do.call(rbind.data.frame, df)
  }
  new_mvt <- make_df(sim_mvt)
  new_mvt
  
  file_name <- name_dataframe(wd = wd,
                              distribution = 'multi', 
                              model = 'ddm', 
                              design = 'bs', 
                              n = pp, 
                              size = size, 
                              reruns = reruns)
  save(sim_mvt, file = file_name)
  sim_mvt
}
