source("logistic_simulations.R")
library(MASS)
library(visdat)
library(tidyverse)
library(data.table)
library(readxl)
library(rtdists)
library(xtable)
library(afex)
library(emmeans)
library(dplyr)
library(fitdistrplus)
library(truncdist)
#directory where you want to save the files
wd <- "/Users/ruslanatymchyk/Documents/MSc Behavioural Economics/Dissertation/masters-diss/UPDATED_CODE/simulated_data"
#-----------------------------------------------------------
# distribution: uni, multi
# model: log, ddm
# design: bs, rm
# n: number of participants
# size: number or trials per participant
# reruns: number of datasets to be simulated
name_dataframe <- function(wd, distribution, model, design, n, size, reruns){
  properties <- c(wd, "/",
                  distribution, "_", 
                  model, "_", 
                  design, "_", 
                  n, "pp", 
                  size, "tr", reruns, "runs.rda")
  #each property has to be a string
  newname <- paste(properties, collapse = "")
  #newname <- oldname #make new dataset point to an old one
  print(newname)
  newname
}
#-----------------------------------------------------------------------------------
#------Logistic Between Subjects-----------------------------------------------------------
#-----------------------------------------------------------------------------------
#Parameters
# n: number of participants (does it need to be divided by 2???)
# size: number or trials per participant
# reruns: number of datasets to be simulated (NOTE, if reruns = 1, 
# 10 datasets will be produced, 1 for each probability)
#Output
# aov_p: p-value generated by ANOVA
# glm_p: p-value generated by GLM
# diff_props: difference in proportion of successes between groups
# mean_prop_real: mean proportion of success for both groups combined 
#(meant to converge with prob for large samples)
# g1_prop: proportion of successes for group 1
# g2_prop: proportion of successes for group 2
# n: number of participants
# size: number or trials per participant
# prob :probability of success for an experiment (same for both groups)
#-----------------------------------------------------------
simulate_logistic_bs <- function(n, size, reruns){
  probs <- seq(0.5, 0.975, by = 0.05)
  simulated_data <- mapply(rerun_logistic_bs, prob = probs,
                           MoreArgs = list(n = n, 
                                           size = size, 
                                           reruns = reruns))
  simulated_data <- as.data.frame(simulated_data)
  simulated_data <- do.call(rbind.data.frame, simulated_data)
  rownames(simulated_data) <- NULL
  
  file_name <- name_dataframe(wd = wd,
                              distribution = 'uni', 
                              model = 'log', 
                              design = 'bs', 
                              n = n, 
                              size = size, 
                              reruns = reruns)
  save(simulated_data, file = file_name)
  simulated_data 
}

#-----------------------------------------------------------------------------------
#------Logistic Repeated Measures-----------------------------------------------------------
#-----------------------------------------------------------------------------------
#Parameters
# n: number of participants (does it need to be divided by 2???)
# size: number or trials per participant
# reruns: number of datasets to be simulated (NOTE, if reruns = 1, 
# 10 datasets will be produced, 1 for each probability)
#Output
# aov_p: p-value generated by ANOVA
# glmm_p: p-value generated by GLMM
# diff_props: difference in proportion of successes between frames(gain vs loss)
# mean_prop_real: mean proportion of success for both frames combined 
#(meant to converge with prob for large samples)
# frame1_prop: proportion of successes for frame 1
# frame2_prop: proportion of successes for frame 2
# n: number of participants
# size: number or trials per participant
# prob :probability of success for an experiment (same for both groups)
#-----------------------------------------------------------
simulate_logistic_rm <- function(n, size, reruns){
  probs <- seq(0.5, 0.975, by = 0.05)
  simulated_data <- mcmapply(rerun_logistic_rm, prob = probs,
                           MoreArgs = list(n = n, 
                                           size = size, 
                                           reruns = reruns),
                           mc.cores = 2)
  simulated_data <- as.data.frame(simulated_data)
  simulated_data <- do.call(rbind.data.frame, simulated_data)
  rownames(simulated_data) <- NULL
  file_name <- name_dataframe(wd = wd, 
                              distribution = 'uni', 
                              model = 'log', 
                              design = 'rm', 
                              n = n, 
                              size = size, 
                              reruns = reruns)
  save(simulated_data, file = file_name)
  simulated_data
  print(simulated_data)
}
